name: dart_queue
description: A starting point for Dart libraries or applications.
version: 1.0.1
homepage: https://github.com/rknell/dart_queue
repository: https://github.com/rknell/dart_queue

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  extra_pedantic: 1.1.1
  pedantic:
  test: ^1.6.0
