name: queue
description: Queue up futures from multiple sources and await their return anywhere in your code.
version: 3.1.0+1
homepage: https://github.com/rknell/dart_queue
repository: https://github.com/rknell/dart_queue

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  extra_pedantic: 1.3.0
  pedantic: 1.10.0
  test: ^1.16.3
