name: Test

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: google/dart:2

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Run tests
        run: pub run test
      - name: Run analyzer
        run: dartanalyzer .
